@startuml diagram router getTask 
start
:Receive request; 
if (check url = "/tasks?status={statusTask}") then (no) 
    :Response status code: error 404(not found);
    else (yes) 
        if (method = "GET"?) then (no)
            :Response status code: error 405(method is not correct);
                else (yes) 
                    :Call function filterTask of controller;
                    :Controller response to browser;
        endif
endif
stop
@enduml