@startuml diagram router updateTask 
start
:Receive request; 
if (check url = "/tasks/{id}") then (no) 
    :Response status code: error 404(not found);
    else (yes) 
        if (method = "PUT"?) then (no)
            :Response status code: error 405(method is not correct);
                else (yes) 
                    :Call function editTask of controller;
                    :Controller response to browser;
        endif
endif
stop
@enduml